version: '2'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
      - /usr/app/client/node_modules
    ports:
      - '8080:8080'
      - '3000:3000'
